//
// Created by bigdata-wgf on 2021/12/8.
//

#ifndef INC_3DBODY_3DBODY_INCLUDE_EVENT_HANDLING_EVENT_BASE_H_
#define INC_3DBODY_3DBODY_INCLUDE_EVENT_HANDLING_EVENT_BASE_H_


namespace gf{

enum class EVENT_SOURCE_TYPE{
  NONE=0,
  KEYBOARD,
  MOUSE,
  JOYSTICK,
  TIME_INPUT,
  CLIPBOARD,
  PATH_DROP
};

enum class EVENT_ACTION{
  NONE=0,
  PRESSED,
  RELEASE,
  HOVERED
};

}

#endif //INC_3DBODY_3DBODY_INCLUDE_EVENT_HANDLING_EVENT_BASE_H_
